universe   = vanilla
getenv     = true
# run script -- make sure that condor has execute permission for this file (chmod a+x script.py)
executable = /work/jahed.abedi/projects/Echoes/GW190521/run/NRSur7dq4_2/run.sh
# file to dump stdout (this directory should exist)
output     = /work/jahed.abedi/projects/Echoes/GW190521/run/NRSur7dq4_2/logs/echoes_$(Process).out
# file to dump stderr
error     = /work/jahed.abedi/projects/Echoes/GW190521/run/NRSur7dq4_2/logs/echoes_$(Process).err 
# condor logs
log     = /work/jahed.abedi/projects/Echoes/GW190521/run/NRSur7dq4_2/logs/echoes_$(Process).log 
initialdir = /work/jahed.abedi/projects/Echoes/GW190521/run/NRSur7dq4_2
notification = Never
arguments  = "-processid $(Process)"
request_memory = 64GB
request_cpus = 48
on_exit_remove = (ExitBySignal == False) || ((ExitBySignal == True) && (ExitSignal != 11))
accounting_group = cbc.imp.echoes
queue 1

